### ISSUE TITLE
installation problem (IDA 7.4 Python 3.8 @ Windows 10)

### ISSUE THREAD

**Issue by xdavidel** [CheckPointSW/Karta#36]
Following the README Python3 instructions led to the following error at installation:
```
Traceback (most recent call last):
  File "C:\Users\David\Desktop\Karta-master\setup.py", line 9, in <module>
    setup(name='Karta',
  File "C:\Python\Python38\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Python\Python38\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python\Python38\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Python\Python38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Python\Python38\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Python\Python38\lib\site-packages\setuptools\command\install.py", line 117, in do_egg_install
    cmd.run()
  File "C:\Python\Python38\lib\site-packages\setuptools\command\easy_install.py", line 418, in run
    self.easy_install(spec, not self.no_deps)
  File "C:\Python\Python38\lib\site-packages\setuptools\command\easy_install.py", line 660, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "C:\Python\Python38\lib\site-packages\setuptools\command\easy_install.py", line 707, in install_item
    self.process_distribution(spec, dist, deps)
  File "C:\Python\Python38\lib\site-packages\setuptools\command\easy_install.py", line 751, in process_distribution
    distros = WorkingSet([]).resolve(
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
    dist = best[req.key] = env.best_match(
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "C:\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
    return installer(requirement)
  File "C:\Python\Python38\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "C:\Python\Python38\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "C:\Python\Python38\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "C:\Python\Python38\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "C:\Python\Python38\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
    run_setup(setup_script, args)
  File "C:\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
    raise
  File "C:\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
    yield
  File "C:\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "C:\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "C:\Python\Python38\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
    yield saved
  File "C:\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
    yield
  File "C:\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "C:\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "C:\Users\David\AppData\Local\Temp\easy_install-qven3kou\scikit-learn-0.22.1\setup.py", line 303, in <module>
  File "C:\Users\David\AppData\Local\Temp\easy_install-qven3kou\scikit-learn-0.22.1\setup.py", line 299, in setup_package
  File "C:\Python\Python38\lib\site-packages\numpy\distutils\core.py", line 137, in setup
    config = configuration()
  File "C:\Users\David\AppData\Local\Temp\easy_install-qven3kou\scikit-learn-0.22.1\setup.py", line 182, in configuration
  File "C:\Python\Python38\lib\site-packages\numpy\distutils\misc_util.py", line 1033, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "C:\Python\Python38\lib\site-packages\numpy\distutils\misc_util.py", line 999, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "C:\Python\Python38\lib\site-packages\numpy\distutils\misc_util.py", line 941, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "sklearn\setup.py", line 86, in configuration
  File "C:\Users\David\AppData\Local\Temp\easy_install-qven3kou\scikit-learn-0.22.1\sklearn\_build_utils\__init__.py", line 75, in cythonize_extensions
  File "C:\Python\Python38\lib\site-packages\Cython\Build\Dependencies.py", line 1072, in cythonize
    pool = multiprocessing.Pool(
  File "C:\Python\Python38\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\Python\Python38\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "C:\Python\Python38\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "C:\Python\Python38\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "C:\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Python\Python38\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "C:\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 70, in __init__
    with open(wfd, 'wb', closefd=True) as to_child:
  File "C:\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 417, in _open
    if mode not in ('r', 'rt', 'rb', 'rU', 'U') and not self._ok(path):
  File "C:\Python\Python38\lib\site-packages\setuptools\sandbox.py", line 428, in _ok
    realpath = os.path.normcase(os.path.realpath(path))
  File "C:\Python\Python38\lib\ntpath.py", line 626, in realpath
    path = normpath(path)
  File "C:\Python\Python38\lib\ntpath.py", line 452, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not int
```

**Comment by chkp-eyalit** [comment]
Hi, it looks like an installation problem in the "scikit-learn-0.22.1" package, which is required for Thumbs-Up. I will try to reproduce it on my machine and check how to solve it, as I didn't see it before.

**Comment by chkp-eyalit** [comment]
My install was a python 3.7 (Windows 10) and "scikit_learn-0.22rc2.post1" and it worked. It looks like a bug in scikit, will try to check if they have an open issue about it.

**Comment by chkp-eyalit** [comment]
Closed due to lack of activity. Feel free to reopen if the issue persists.
