### ISSUE TITLE
problem running karta scripts in IDA 7.4

### ISSUE THREAD

**Issue by stranger010101** [CheckPointSW/Karta#53]
I am trying to run Karta scripts in IDA but I get the following error:

Karta - INFO: Chose the IDA handler[0m
 Karta - ERROR: Failed to create disassembler handler "IDA": DLL load failed while importing sip: The specified module could not be found. Karta - ERROR: Traceback (most recent call last):
                                         File "C:/Users/User/Karta/src\disassembler\factory.py", line 55, in createDisassemblerHandler
                                           return verifier.disas()
                                         File "C:/Users/User/Karta/src\disassembler\IDA\ida_verifier_api.py", line 42, in disas
                                           from .ida_api import IDA
                                         File "C:/Users/User/Karta/src\disassembler\IDA\ida_api.py", line 9, in <module>
                                           import sark
                                         File "C:\Python38\lib\site-packages\sark-7.4.0-py3.8.egg\sark\__init__.py", line 14, in <module>
                                           from . import (core,
                                         File "C:\Python38\lib\site-packages\sark-7.4.0-py3.8.egg\sark\code\__init__.py", line 10, in <module>
                                           from . import line
                                         File "C:\Python38\lib\site-packages\sark-7.4.0-py3.8.egg\sark\code\line.py", line 7, in <module>
                                           from ..ui import updates_ui
                                         File "C:\Python38\lib\site-packages\sark-7.4.0-py3.8.egg\sark\ui.py", line 6, in <module>
                                           from .qt import MenuManager
                                         File "C:\Python38\lib\site-packages\sark-7.4.0-py3.8.egg\sark\qt.py", line 4, in <module>
                                           from PyQt5 import QtCore, QtWidgets, QtGui
                                       ImportError: DLL load failed while importing sip: The specified module could not be found.
                                       [0m

I installed every repository required but still cant run it. Will be glad to get some help.

**Comment by chkp-eyalit** [comment]
Hi, sorry about the dependency issue. Python's versions and packages are a mess.
We had someone with a similar issue before, and it seems that IDA (at least in 7.4) compiled their PyQt against python 3.6, and it isn't interoperable with python 3.8 as you have it. Using python 3.6 with your IDA should work (even if it feel our of place).

Personally, I'm using python 3.7 with my IDA (all 7.X versions), and it works smooth.

**Comment by stranger010101** [comment]
Works with python 3.7
Thank you!

**Comment by chkp-eyalit** [comment]
Great! Happy to hear it solved your issue.
