### ISSUE TITLE
the problem of karta_identifier.py

### ISSUE THREAD

**Issue by jackwolail** [CheckPointSW/Karta#62]
Karta - INFO: Chose the IDA handler[0m
[91m[11/08/2022 12:57:36] - Karta - ERROR: Failed to create disassembler handler "IDA": DLL load failed while importing sip: 找不到指定的模块。[0m
[91m[11/08/2022 12:57:36] - Karta - ERROR: Traceback (most recent call last):
                                         File "D:\ChromeCoreDownloads/Karta-2.1.0/src\disassembler\factory.py", line 55, in createDisassemblerHandler
                                           return verifier.disas()
                                         File "D:\ChromeCoreDownloads/Karta-2.1.0/src\disassembler\IDA\ida_verifier_api.py", line 42, in disas
                                           from .ida_api import IDA
                                         File "D:\ChromeCoreDownloads/Karta-2.1.0/src\disassembler\IDA\ida_api.py", line 9, in <module>
                                           import sark
                                         File "D:\Python3.9.13\lib\site-packages\sark-7.4.1-py3.9.egg\sark\__init__.py", line 14, in <module>
                                           from . import (core,
                                         File "D:\Python3.9.13\lib\site-packages\sark-7.4.1-py3.9.egg\sark\code\__init__.py", line 10, in <module>
                                           from . import line
                                         File "D:\Python3.9.13\lib\site-packages\sark-7.4.1-py3.9.egg\sark\code\line.py", line 7, in <module>
                                           from ..ui import updates_ui
                                         File "D:\Python3.9.13\lib\site-packages\sark-7.4.1-py3.9.egg\sark\ui.py", line 6, in <module>
                                           from .qt import MenuManager
                                         File "D:\Python3.9.13\lib\site-packages\sark-7.4.1-py3.9.egg\sark\qt.py", line 4, in <module>
                                           from PyQt5 import QtCore, QtWidgets, QtGui
                                       ImportError: DLL load failed while importing sip: 找不到指定的模块。

**Comment by MambaInVeins** [comment]
I met the same problem, how to solve it?
